export const fields = {
  employeeCode: {
    label: "Mã NV",
    title: "Mã nhân viên",
    name: "employeeCode",
    maxLength: 20,
    type: "text",
  },
  fullName: {
    label: "Họ và tên",
    name: "fullName",
    maxLength: 100,
    type: "text",
  },
  department: {
    label: "Phòng ban",
    name: "department",
    maxLength: 255,
    type: "text",
  },
  position: {
    label: "Chức danh",
    name: "position",
    maxLength: 100,
    type: "text",
  },
  dateOfBirth: {
    label: "Ngày sinh",
    name: "dateOfBirth",
    type: "date",
  },
  gender: {
    label: "Giới tính",
    name: "gender",
    type: "text",
  },
  identityNumber: {
    label: "Số CMND",
    title: "Số chứng minh nhân dân",
    name: "identityNumber",
    maxLength: 25,
    type: "text",
  },
  identityDate: {
    label: "Ngày cấp",
    name: "identityDate",
    type: "date",
  },
  identityPlace: {
    label: "Nơi cấp",
    name: "identityPlace",
    maxLength: 255,
    type: "text",
  },
  address: {
    label: "Địa chỉ",
    name: "address",
    maxLength: 255,
    type: "text",
  },
  phoneNumber: {
    label: "ĐT di động",
    title: "Điện thoại di động",
    name: "phoneNumber",
    maxLength: 50,
    type: "text",
  },
  landlineNumber: {
    label: "ĐT cố định",
    title: "Điện thoại cố định",
    name: "phoneNumber",
    maxLength: 50,
    type: "text",
  },
  email: {
    label: "Email",
    name: "email",
    maxLength: 100,
    type: "text",
  },
  bankAccount: {
    label: "Số tài khoản",
    name: "bankAccount",
    maxLength: 25,
    type: "text",
  },
  bankName: {
    label: "Tên ngân hàng",
    name: "bankName",
    maxLength: 255,
    type: "text",
  },
  bankBranch: {
    label: "Chi nhánh ngân hàng",
    name: "bankBranch",
    maxLength: 255,
    type: "text",
  },
  personalTaxCode: {
    label: "Mã số thuế",
    name: "personalTaxCode",
    maxLength: 25,
    type: "text",
  },
  salary: {
    label: "Lương",
    name: "salary",
    maxLength: 50,
    type: "text",
  },
};