const vn = {
  error: "Lỗi",
  success: "Thành công",
  warning: "Cảnh báo",
  info: "Thông tin",
  notice: "Thông báo",
  selectValue: "Chọn giá trị",
  typeFilterValue: "Nhập giá trị lọc",
  valueNotInSelects: "Giá trị không có trong danh sách",
  cannotEmpty: "không được để trống",
  onlyDigit: "chỉ được bao gồm số",
  invalidPhoneNumber: "Số điện thoại phải là số từ 9 - 11 ký tự",
  invalidIdentityNumber: "Số CCCD phải là số có 9 hoặc 12 ký tự",
  invalidEmail: "Email sai định dạng",
  cannotBiggerToday: "không thể lớn hơn hôm nay",
  male: "Nam",
  female: "Nữ",
  other: "Khác",
  checkAgain: "Vui lòng kiểm tra lại",
  notInSelects: "không có trong danh sách",
  createEmployee: "Thêm mới nhân viên",
  updateEmployee: "Cập nhật nhân viên",
  duplicateEmployee: "Nhân bản nhân viên",
  deletedEmployee: "Đã xoá nhân viên",
  delete: "Xoá",
  deleted: "Đã xoá",
  cannotDelete: "Không thể xoá",
  deleteConfirm: "Xác nhận xoá",
  employee: "nhân viên",
  titleEmployees: "Nhân viên",
  titleHome: "Tổng quan",
  accountingAmis: "AMIS Kế toán",
  employeeList: "Danh sách nhân viên",
  employeeListFileName: "Danh_sach_nhan_vien",
  selectedEmployees: "nhân viên đã chọn",
  reloadedData: "Đã làm mới dữ liệu",
  create: "Thêm mới",
  created: "Đã thêm",
  duplicated: "Đã nhân bản",
  updated: "Đã cập nhật",
  invalidFormMessage: "Một số trường không hợp lệ. Vui lòng kiểm tra lại.",
  employeeCode: "Mã nhân viên",
  identity: "Số CCCD",
  phone: "Điện thoại di động",
  userMsg500:
    "Có lỗi xảy ra. Vui lòng thử lại sau.\nHoặc liên hệ bộ phận IT của công ty.",
  userMsg400: "Yêu cầu không hợp lệ. Vui lòng kiểm tra lại.",
  noContent: "Không có dữ liệu",
  save: "Cất",
  saveAdd: "Cất và thêm",
  saveChange: "Cất thay đổi",
  saveChangeConfirm:
    "Dữ liệu đã bị thay đổi so với lúc đầu.\nBạn có muốn cất không?",
  gotIt: "Đã hiểu",
  cancel: "Huỷ",
  no: "Không",
  duplicatedEmployeeCode: "Mã nhân viên bị trùng",
  mustLessThan: "phải nhỏ hơn",
  char: "ký tự",
  cannotConnectServer: "Không thể kết nối đến máy chủ. Vui lòng kiểm tra lại.",
  futureFeature: "Chức năng sắp được hoàn thiện. Vui lòng thử lại sau.",
  connectTimeOut: "Quá thời gian kết nối. Vui lòng thử lại.",
  serverNoResponse: "Máy chủ không phản hồi. Vui lòng thử lại sau.",
  busySystem: "Hệ thống đang bận. Vui lòng thử lại sau.",
  contain: "Chứa",
  equal: "Bằng",
  less: "Nhỏ hơn",
  more: "Lớn hơn",
  empty: "Rỗng",
  startWith: "Bắt đầu bằng",
  endWith: "Kết thúc bằng",
  before: "Trước",
  after: "Sau",
  monthEqual: "Có tháng bằng",
  yearEqual: "Có năm bằng",
  month: "Tháng",
  typeMonth: "Nhập tháng",
  year: "Năm",
  typeYear: "Nhập năm",
  filterValue: "Giá trị lọc",
  filter: "Lọc",
  sort: "Sắp xếp",
  invalid: "không hợp lệ",
  searchResult: "Kết quả tìm kiếm",
  required: "Bắt buộc",
  actionMany: "Thực hiện hàng loạt",
  fix: "Sửa",
  unselect: "Bỏ chọn",
  removeFilter: "Bỏ lọc",
  removeSearch: "Bỏ tìm kiếm",
  today: "Hôm nay",
  removeAllFilters: "Bỏ tất cả lọc",
  searchEmployee: "Tìm kiếm theo mã, tên, số điện thoại, email",
  searchEmployeeShort: "Tìm theo mã, tên, sđt, email",
  searchInList: "Tìm kiếm trong danh sách",
  exportToExcel: "Xuất file excel",
  reloadData: "Làm mới",
  invalidDateddMMyyyy: "phải có định dạng dd/MM/yyyy",
  invalidDateyyyyMMdd: "phải có định dạng yyyy/MM/dd",
  invalidDate: "không hợp lệ",
  total: "Tổng",
  selectedCount: "Đã chọn",
  percentage: "Tỉ lệ",
  selected: "đã chọn",
  unSelect: "Bỏ chọn",
  home: "Tổng quan",
  record: "Bản ghi",
  recordsPerPage: "Số bản ghi/trang",
  getNewCode: "Lấy mã mới",
};

const resources = {
  vn: vn,
};
export default resources;
